blank_issues_enabled: true
pull_request_templates:
  - name: ðŸ§¹ Chore / DevOps
    path: .github/PULL_REQUEST_TEMPLATE/chore.md
  - name: ðŸ§ª Testing
    path: .github/PULL_REQUEST_TEMPLATE/testing.md
  - name: ðŸ“¦ Default
    path: .github/PULL_REQUEST_TEMPLATE/default.md